Repository 742PM/Quiz, pull requests merged in 2019-05, with the labels that each got.

#82 Error handling implemented
  Complexity/Application/IQuizService.cs
  Complexity/Application/Selectors/RandomTaskGeneratorSelector.cs
  Complexity/ComplexityWeb/Controllers/QuizServiceController.cs
Labels: backend

#87 Рефакторинг Database Filler
  Complexity/DataBase/DatabaseFiller.cs
  Complexity/DataBase/MongoDatabaseInitializer.cs
  Complexity/DataBase/Program.cs
Labels: database, frontend

#97 Add task service interface
  Complexity/Application/ITaskService.cs
Labels: backend, database

#100 add None type
  Complexity/Infrastructure/Result/None.cs
Labels: backend

#99 Обновление сервиса
  Complexity/Application/Extensions/DomainExtensions.cs
  Complexity/Application/IQuizService.cs
  Complexity/Application/Info/HintInfo.cs
  Complexity/Application/Info/LevelProgressInfo.cs
  Complexity/Application/Info/TaskInfo.cs
  Complexity/Application/QuizService.cs
  Complexity/ComplexityWeb/Controllers/QuizServiceController.cs
  Complexity/ComplexityWeb/DTO/HintInfoDTO.cs
  Complexity/ComplexityWeb/DTO/LevelProgressInfoDTO.cs
  Complexity/ComplexityWeb/DTO/TaskInfoDTO.cs
  Complexity/ComplexityWeb/Startup.cs
Labels: backend, important

#107 Пофиксил баг с подсказками
  Complexity/ComplexityWeb/DTO/TaskInfoDTO.cs
  Complexity/DataBase/MongoDatabaseInitializer.cs
Labels: backend, bug

#110 Добавил Task service
  Complexity/Application/Extensions/DataBaseExtensions.cs
  Complexity/Application/Extensions/LoggerExtensions.cs
  Complexity/Application/QuizService/IQuizService.cs
  Complexity/Application/QuizService/QuizService.cs
  Complexity/Application/Repositories/ITaskRepository.cs
  Complexity/Application/TaskService/ITaskService.cs
  Complexity/Application/TaskService/TaskService.cs
  Complexity/ComplexityWeb/Controllers/QuizServiceController.cs
  Complexity/ComplexityWeb/Controllers/TaskServiceController.cs
  Complexity/ComplexityWeb/Startup.cs
  Complexity/DataBase/MongoTaskRepository.cs
  Complexity/Infrastructure/Result/None.cs
  Complexity/Tests/ApplicationTests.cs
  Complexity/Tests/Mocks/TestTaskRepository.cs
Labels: backend, database

#108 Template creator app
  Complexity/Application/Extensions/DomainExtensions.cs
  Complexity/Complexity.sln
  Complexity/Complexity.sln.DotSettings
  Complexity/DataBase/MongoDatabaseInitializer.cs
  Complexity/Domain/Domain.csproj
  Complexity/Domain/Entities/Level.cs
  Complexity/Domain/Entities/TaskGenerators/TaskGenerator.cs
  Complexity/Domain/Entities/TaskGenerators/TemplateLanguage.cs
  Complexity/Domain/Entities/TaskGenerators/TemplateLanguageSettings.cs
  Complexity/Domain/Entities/TaskGenerators/TemplateTaskGenerator.cs
  Complexity/Domain/Entities/Topic.cs
  Complexity/Domain/Values/Task.cs
  Complexity/Infrastructure/ArrayExtensions.cs
  Complexity/Infrastructure/EnumerableExtensions.cs
  Complexity/Infrastructure/Storage.cs
  Complexity/Infrastructure/StorageExtensions.cs
  Complexity/Infrastructure/StringExtensions.cs
  Complexity/Tests/Mocks/TestGenerator.cs
  Complexity/Tests/Storage_Should.cs
  Complexity/Tests/TemplateGenerator_Should.cs
  Complexity/Tests/TemplateTaskGenerator_Should.cs
Labels: backend

#114 Fail safety
  Complexity/Application/Extensions/DataBaseExtensions.cs
  Complexity/Application/Extensions/DomainExtensions.cs
  Complexity/Application/QuizService/QuizService.cs
  Complexity/Infrastructure/EnumerableExtensions.cs
  Complexity/Infrastructure/KeyComparer.cs
Labels: backend

#115 Исправил документацию QuizServiceController
  Complexity/Application/QuizService/IQuizService.cs
  Complexity/Application/QuizService/QuizService.cs
  Complexity/ComplexityWeb/Controllers/QuizServiceController.cs
  Complexity/Tests/ApplicationTests.cs
Labels: bug

#116 Fix database and add question field to task
  Complexity/Application/TaskService/ITaskService.cs
  Complexity/Application/TaskService/TaskService.cs
  Complexity/ComplexityWeb/Controllers/TaskServiceController.cs
  Complexity/ComplexityWeb/DTO/DataBaseTemplateGeneratorDTO.cs
  Complexity/ComplexityWeb/DTO/DataBaseTemplateGeneratorWithStreakDTO.cs
  Complexity/DataBase/DatabaseFiller.cs
  Complexity/Domain/Entities/TaskGenerators/TemplateTaskGenerator.cs
Labels: backend, bug, database

#117 Create mappings for task service and something else
  Complexity/ComplexityWeb/Controllers/TaskServiceController.cs
  Complexity/ComplexityWeb/DTO/AdminLevelDTO.cs
  Complexity/ComplexityWeb/DTO/AdminTaskGeneratorDTO.cs
  Complexity/ComplexityWeb/DTO/AdminTopicDTO.cs
  Complexity/ComplexityWeb/Startup.cs
  Complexity/Domain/Entities/Level.cs
Labels: bug, important

#119 Level manager ui
  Complexity/ComplexityWeb/.babelrc
  Complexity/ComplexityWeb/App/boot.jsx
  Complexity/ComplexityWeb/App/components/App.js
  Complexity/ComplexityWeb/App/components/Editor.js
  Complexity/ComplexityWeb/App/components/forms/CreateGeneratorForm.js
  Complexity/ComplexityWeb/App/components/forms/CreateLevelForm.js
  Complexity/ComplexityWeb/App/components/forms/CreateTopicForm.js
  Complexity/ComplexityWeb/App/components/forms/DeleteGeneratorForm.js
  Complexity/ComplexityWeb/App/components/forms/DeleteLevelForm.js
  Complexity/ComplexityWeb/App/components/forms/DeleteTopicForm.js
  Complexity/ComplexityWeb/App/components/forms/RenderTaskForm.js
  Complexity/ComplexityWeb/App/components/login/LoginForm.js
  Complexity/ComplexityWeb/App/components/login/RightsViewer.js
  Complexity/ComplexityWeb/App/components/login/Welcom.js
  Complexity/ComplexityWeb/App/components/login/auth.js
  Complexity/ComplexityWeb/ComplexityWebApi.csproj
  Complexity/ComplexityWeb/Controllers/TaskServiceController.cs
  Complexity/ComplexityWeb/Startup.cs
  Complexity/ComplexityWeb/package-lock.json
  Complexity/ComplexityWeb/package.json
  Complexity/ComplexityWeb/webpack.config.js
  Complexity/ComplexityWeb/webpack.config.vendor.js
  Complexity/ComplexityWeb/wwwroot/favicon.ico
  Complexity/ComplexityWeb/wwwroot/index.html
Labels: deploy, frontend, in development

#122 History filler
  Quiz/DataBase/ComplexityDatabaseFiller.cs
  Quiz/DataBase/DatabaseFiller.cs
  Quiz/DataBase/HistoryDatabaseFiller.cs
  Quiz/DataBase/IDatabaseFiller.cs
  Quiz/DataBase/Program.cs
  Quiz/Domain/Entities/TaskGenerators/TemplateLanguageSettings.cs
Labels: database

#124 Topic id bug
  Quiz/Application/Extensions/DataBaseExtensions.cs
  Quiz/Application/Extensions/DomainExtensions.cs
  Quiz/Application/QuizService/IQuizService.cs
  Quiz/Application/QuizService/QuizService.cs
  Quiz/ComplexityWeb/Controllers/QuizServiceController.cs
Labels: backend, bug, database

#127 Обновление базы данных при запросах
  Quiz/Application/Extensions/DataBaseExtensions.cs
  Quiz/Application/Extensions/DomainExtensions.cs
  Quiz/Application/Extensions/LoggerExtensions.cs
  Quiz/Application/QuizService/QuizService.cs
  Quiz/Application/Repositories/Entities/LevelProgressEntity.cs
  Quiz/Application/Repositories/Entities/TopicProgressEntity.cs
  Quiz/Application/Selectors/RandomTaskGeneratorSelector.cs
  Quiz/Application/TaskService/TaskService.cs
  Quiz/Domain/Entities/TaskGenerators/TemplateLanguageSettings.cs
  Quiz/Domain/Entities/TaskGenerators/TemplateTaskGenerator.cs
  Quiz/Infrastructure/Extensions/ArrayExtensions.cs
  Quiz/Infrastructure/Extensions/DictionaryExtensions.cs
  Quiz/Infrastructure/Extensions/EnumerableExtensions.cs
  Quiz/Infrastructure/Extensions/ObjectExtensions.cs
  Quiz/Infrastructure/Extensions/StorageExtensions.cs
  Quiz/Infrastructure/Extensions/StringExtensions.cs
  Quiz/Infrastructure/Storage.cs
  Quiz/Tests/Storage_Should.cs
Labels: backend, bug, database

#128 Добавил стрики в филлер
  Quiz/ComplexityWeb/Controllers/TaskServiceController.cs
  Quiz/DataBase/ComplexityDatabaseFiller.cs
Labels: backend, database

#138 Пофиксил апи для редактора
  Quiz/Application/Extensions/DomainExtensions.cs
  Quiz/Application/TaskService/ITaskService.cs
  Quiz/Application/TaskService/TaskService.cs
  Quiz/ComplexityWeb/Controllers/TaskServiceController.cs
  Quiz/ComplexityWeb/DTO/AdminLevelDTO.cs
  Quiz/ComplexityWeb/DTO/AdminTopicDTO.cs
  Quiz/ComplexityWeb/DTO/DataBaseLevelDTO.cs
  Quiz/ComplexityWeb/DTO/DataBaseTemplateGeneratorDTO.cs
  Quiz/ComplexityWeb/DTO/DataBaseTemplateGeneratorWithStreakDTO.cs
  Quiz/ComplexityWeb/QuizService/DTO/HintInfoDTO.cs
  Quiz/ComplexityWeb/QuizService/DTO/LevelInfoDTO.cs
  Quiz/ComplexityWeb/QuizService/DTO/LevelProgressInfoDTO.cs
  Quiz/ComplexityWeb/QuizService/DTO/TaskInfoDTO.cs
  Quiz/ComplexityWeb/QuizService/DTO/TopicInfoDTO.cs
  Quiz/ComplexityWeb/QuizService/QuizServiceController.cs
  Quiz/ComplexityWeb/Startup.cs
  Quiz/ComplexityWeb/TaskService/DTO/AdminTemplateGeneratorDTO.cs
  Quiz/ComplexityWeb/TaskService/DTO/EmptyLevelDTO.cs
  Quiz/ComplexityWeb/TaskService/DTO/EmptyTopicDTO.cs
  Quiz/ComplexityWeb/TaskService/DTO/TemplateGeneratorDTO.cs
  Quiz/ComplexityWeb/TaskService/DTO/TemplateGeneratorForRenderDTO.cs
  Quiz/ComplexityWeb/TaskService/TaskServiceController.cs
Labels: backend, bug

#144 Level manager ui
  Quiz/QuizLevelManager/ClientApp/package-lock.json
  Quiz/QuizLevelManager/ClientApp/package.json
  Quiz/QuizLevelManager/ClientApp/src/components/forms/CreateGeneratorForm.js
  Quiz/QuizLevelManager/ClientApp/src/components/forms/CreateLevelForm.js
  Quiz/QuizLevelManager/ClientApp/src/components/forms/CreateTopicForm.js
  Quiz/QuizLevelManager/ClientApp/src/components/forms/DeleteGeneratorForm.js
  Quiz/QuizLevelManager/ClientApp/src/components/forms/DeleteLevelForm.js
  Quiz/QuizLevelManager/ClientApp/src/components/forms/DeleteTopicForm.js
  Quiz/QuizLevelManager/ClientApp/src/components/forms/RenderTaskForm.js
  Quiz/QuizLevelManager/ClientApp/src/components/login/LoginForm.js
  Quiz/QuizLevelManager/ClientApp/src/styles/Login.css
  Quiz/QuizLevelManager/Controllers/ProxyController.cs
  Quiz/QuizLevelManager/Startup.cs
  Quiz/QuizRequestExtendedService/DTO/GuidDTO.cs
  Quiz/QuizRequestExtendedService/IQuizServiceExtended.cs
Labels: backend, deploy, frontend

#162 Fix some bugs with ids
  Quiz/QuizLevelManager/ClientApp/src/components/App.js
  Quiz/QuizLevelManager/ClientApp/src/components/forms/CreateGeneratorForm.js
  Quiz/QuizLevelManager/ClientApp/src/components/forms/DeleteGeneratorForm.js
  Quiz/QuizLevelManager/ClientApp/src/components/forms/DeleteLevelForm.js
Labels: bug, frontend

#155 Использование NextLevels
  Quiz/Application/Extensions/DataBaseExtensions.cs
  Quiz/Application/QuizService/QuizService.cs
  Quiz/Application/TaskService/TaskService.cs
Labels: backend, bug
