Repository 742PM/Quiz, pull requests merged in 2019-06, with the labels that each got.

#164 Загрузка темы одним пакетом
  Quiz/Application/DTO/LevelDTO.cs
  Quiz/Application/DTO/TemplateTaskGeneratorDTO.cs
  Quiz/Application/DTO/TopicDTO.cs
  Quiz/Application/Extensions/DomainExtensions.cs
  Quiz/Application/QuizService/IQuizService.cs
  Quiz/Application/QuizService/QuizService.cs
  Quiz/Application/TaskService/ITaskService.cs
  Quiz/Application/TaskService/TaskService.cs
  Quiz/ComplexityWeb/Extensions/JsonExtensions.cs
  Quiz/ComplexityWeb/Program.cs
  Quiz/ComplexityWeb/QuizWebApp.csproj
  Quiz/ComplexityWeb/RawRequestBodyFormatter.cs
  Quiz/ComplexityWeb/Services/QuizService/DTO/HintInfoDTO.cs
  Quiz/ComplexityWeb/Services/QuizService/DTO/LevelInfoDTO.cs
  Quiz/ComplexityWeb/Services/QuizService/DTO/LevelProgressInfoDTO.cs
  Quiz/ComplexityWeb/Services/QuizService/DTO/TaskInfoDTO.cs
  Quiz/ComplexityWeb/Services/QuizService/DTO/TopicInfoDTO.cs
  Quiz/ComplexityWeb/Services/QuizService/QuizServiceController.cs
  Quiz/ComplexityWeb/Services/TaskService/DTO/AdminTemplateGeneratorDTO.cs
  Quiz/ComplexityWeb/Services/TaskService/DTO/EmptyLevelDTO.cs
  Quiz/ComplexityWeb/Services/TaskService/DTO/EmptyTopicDTO.cs
  Quiz/ComplexityWeb/Services/TaskService/DTO/TemplateGeneratorDTO.cs
  Quiz/ComplexityWeb/Services/TaskService/DTO/TemplateGeneratorForRenderDTO.cs
  Quiz/ComplexityWeb/Services/TaskService/TaskServiceController.cs
  Quiz/ComplexityWeb/Services/TaskService/Uploading_TaskServiceController.cs
  Quiz/ComplexityWeb/Startup.cs
  Quiz/DataBase/DataBase.csproj
  Quiz/DataBase/FillerParts/SingleLoopsFiller.cs
  Quiz/DataBase/MongoDatabaseInitializer.cs
  Quiz/DataBase/ReworkedComplexityFiller.cs
  Quiz/Infrastructure/Extensions/ObjectExtensions.cs
  Quiz/Infrastructure/UnsafeAttribute.cs
  Quiz/QuizBotCore/Commands/ICommand.cs
  Quiz/QuizBotCore/Commands/MessageExtensions.cs
  Quiz/QuizBotCore/Transitions/CancelTransition.cs
  Quiz/QuizLevelManager/Pages/_ViewImports.cshtml
  Quiz/Tests/TemplateTaskGenerator_Should.cs
  Quiz/Tests/ToDTO_Should.cs
Labels: backend, enhancement

#167 Дубликат #164
  Quiz/Application/DTO/TemplateTaskGeneratorDTO.cs
  Quiz/Application/DTO/TopicDTO.cs
  Quiz/Application/Extensions/DomainExtensions.cs
  Quiz/Application/TaskService/ITaskService.cs
  Quiz/Application/TaskService/TaskService.cs
  Quiz/ComplexityWeb/RawRequestBodyFormatter.cs
  Quiz/ComplexityWeb/Services/TaskService/TaskServiceController.cs
  Quiz/ComplexityWeb/Services/TaskService/Uploading_TaskServiceController.cs
  Quiz/DataBase/DataBase.csproj
  Quiz/DataBase/Fillers/ComplexityDatabaseFiller.cs
  Quiz/DataBase/Fillers/HistoryDatabaseFiller.cs
  Quiz/DataBase/Fillers/IDatabaseFiller.cs
  Quiz/DataBase/Fillers/Program.cs
  Quiz/DataBase/Fillers/ReworkedComplexityFiller.cs
  Quiz/DataBase/MongoDatabaseInitializer.cs
  Quiz/DataBase/MongoHelpers.cs
  Quiz/DataBase/QuizService/MongoTaskRepository.cs
  Quiz/DataBase/QuizService/MongoUserRepository.cs
  Quiz/Infrastructure/UnsafeAttribute.cs
  Quiz/Quiz.sln
  Quiz/QuizBotCore/Commands/MessageExtensions.cs
  Quiz/QuizLevelManager/QuizLevelManager.csproj
  Quiz/Tests/ToDTO_Should.cs
Labels: backend

#170 Добавил избранные символы юникода и прочие удобные поля.
  Quiz/ComplexityWeb/Extensions/JsonExtensions.cs
  Quiz/ComplexityWeb/Services/TaskService/TaskServiceController.cs
  Quiz/ComplexityWeb/Services/TaskService/TemplateController.cs
  Quiz/ComplexityWeb/Services/TaskService/Uploading_TaskServiceController.cs
  Quiz/Domain/Entities/TaskGenerators/TemplateLanguage.cs
  Quiz/Domain/Entities/TaskGenerators/TemplateLanguageSettings.cs
  Quiz/Domain/Entities/TaskGenerators/TemplateTaskGenerator.cs
  Quiz/QuizLevelManager/ClientApp/src/components/forms/RenderTaskForm.js
  Quiz/QuizLevelManager/Controllers/ProxyController.cs
  Quiz/QuizLevelManager/QuizLevelManager.csproj
  Quiz/QuizRequestExtendedService/Requester.cs
  Quiz/Tests/TemplateTaskGenerator_Should.cs
Labels: backend, enhancement

#171 Fix code format and naming
  Quiz/ComplexityWeb/Services/TaskService/Uploading_TaskServiceController.cs
Labels: enhancement

#168 Создал БД адаптер для аутентификации
  Quiz/Application/Selectors/ProgressTaskGeneratorSelector.cs
  Quiz/QuizLevelManager/SimpleUserData.cs
  Quiz/QuizLevelManager/Startup.cs
  Quiz/QuizRequestExtendedService/Database/IUserRepository.cs
  Quiz/QuizRequestExtendedService/Database/UserRepository.cs
  Quiz/QuizRequestExtendedService/QuizRequestExtendedService.csproj
Labels: backend, database

#172 Next Task if not solved
  Quiz/Application/QuizService/IQuizService.cs
  Quiz/Application/QuizService/QuizService.cs
Labels: backend

#173 Добавил обработку ошибки парсинга HJSON
  Quiz/ComplexityWeb/Services/TaskService/HJsonParser.cs
  Quiz/ComplexityWeb/Services/TaskService/Uploading_TaskServiceController.cs
  Quiz/Infrastructure/Result/MaybeExtensions.cs
  Quiz/Quiz.sln.DotSettings
  Quiz/QuizLevelManager/QuizLevelManager.csproj
  Quiz/QuizRequestExtendedService/QuizRequestExtendedService.csproj
Labels: backend, bug

#174 #166 + Вынес текст в БД
  Quiz/ComplexityWeb/Services/TaskService/Uploading_TaskServiceController.cs
  Quiz/DataBase/DataBase.csproj
  Quiz/Domain/Domain.csproj
  Quiz/Infrastructure/Extensions/JsonExtensions.cs
  Quiz/Infrastructure/HJsonParser.cs
  Quiz/Infrastructure/Infrastructure.csproj
  Quiz/QuizBotCore/Buttons & CallBacks/ButtonNames.cs
  Quiz/QuizBotCore/Buttons & CallBacks/DialogMessages.cs
  Quiz/QuizBotCore/Commands/CheckTaskCommand.cs
  Quiz/QuizBotCore/Commands/FeedBackCommand.cs
  Quiz/QuizBotCore/Commands/ReportTaskCommand.cs
  Quiz/QuizBotCore/Commands/SelectLevelCommand.cs
  Quiz/QuizBotCore/Commands/SelectTopicCommand.cs
  Quiz/QuizBotCore/Commands/SendReportTaskCommand.cs
  Quiz/QuizBotCore/Commands/ServiceManager.cs
  Quiz/QuizBotCore/Commands/ShowHintCommand.cs
  Quiz/QuizBotCore/Commands/ShowTaskCommand.cs
  Quiz/QuizBotCore/Database/MessageTextRepository.cs
  Quiz/QuizBotCore/ProgressBar/CircleProgressBar.cs
  Quiz/QuizBotCore/QuizBotCore.csproj
  Quiz/QuizBotCore/TelegramStateMachine.cs
  Quiz/QuizRequestExtendedService/QuizRequestExtendedService.csproj
  Quiz/QuizWebHookBot/Controllers/StatusController.cs
  Quiz/QuizWebHookBot/Controllers/UpdateController.cs
  Quiz/QuizWebHookBot/QuizWebHookBot.csproj
  Quiz/QuizWebHookBot/Startup.cs
  Quiz/Tests/Tests.csproj
Labels: backend

#177 Сделал Telegram logger
  Quiz/Application/DTO/LevelDTO.cs
  Quiz/Application/DTO/TopicDTO.cs
  Quiz/ComplexityWeb/Program.cs
  Quiz/ComplexityWeb/Services/TaskService/Uploading_TaskServiceController.cs
  Quiz/ComplexityWeb/Startup.cs
  Quiz/Infrastructure/Infrastructure.csproj
  Quiz/Infrastructure/Logger/BatchingLogger.cs
  Quiz/Infrastructure/Logger/BatchingLoggerOptions.cs
  Quiz/Infrastructure/Logger/BatchingLoggerProvider.cs
  Quiz/Infrastructure/Logger/LogMessage.cs
  Quiz/Infrastructure/Logger/LoggerFactoryExtensions.cs
  Quiz/Infrastructure/Logger/PeriodicityOptions.cs
  Quiz/Infrastructure/Logger/TelegramLoggerOptions.cs
  Quiz/Infrastructure/Logger/TelegramLoggerProvider.cs
  Quiz/QuizWebHookBot/Program.cs
  Quiz/Tests/ApplicationTests.cs
  Quiz/Tests/ToDTO_Should.cs
Labels: backend

#181 Формат Сообщений в логгере
  Quiz/ComplexityWeb/appsettings.json
  Quiz/Infrastructure/Logger/LogMessage.cs
  Quiz/Infrastructure/Logger/TelegramLoggerProvider.cs
  Quiz/QuizLevelManager/Program.cs
  Quiz/QuizWebHookBot/appsettings.json
Labels: enhancement

#183 Requester Upgrade;
  Quiz/ComplexityWeb/Services/TaskService/Uploading_TaskServiceController.cs
  Quiz/Infrastructure/Result/MaybeExtensions.cs
  Quiz/QuizBotCore/Buttons & CallBacks/DialogMessages.cs
  Quiz/QuizBotCore/Commands/CheckTaskCommand.cs
  Quiz/QuizBotCore/Commands/NoConnectionCommand.cs
  Quiz/QuizBotCore/Commands/SelectLevelCommand.cs
  Quiz/QuizBotCore/Commands/SelectTopicCommand.cs
  Quiz/QuizBotCore/Commands/ShowHintCommand.cs
  Quiz/QuizBotCore/Commands/ShowTaskCommand.cs
  Quiz/QuizBotCore/Parser/MessageParser.cs
  Quiz/QuizBotCore/TelegramStateMachine.cs
  Quiz/QuizRequestService/IQuizService.cs
  Quiz/QuizRequestService/QuizRequestService.csproj
  Quiz/QuizRequestService/Requester.cs
  Quiz/Tests/TelegramStateMachineTests.cs
Labels: backend, important
