Repository 742PM/Quiz, pull requests merged in 2019-04, with the labels that each got.

#64 Перенос интерфейсов репозиториев в Application #56
  Complexity/Application/Application.cs
  Complexity/Application/Application.csproj
  Complexity/Application/DataBaseExtensions.cs
  Complexity/Application/DomainExtensions.cs
  Complexity/Application/Repositories/Entities/LevelProgressEntity.cs
  Complexity/Application/Repositories/Entities/TaskInfoEntity.cs
  Complexity/Application/Repositories/Entities/TopicProgressEntity.cs
  Complexity/Application/Repositories/Entities/UserEntity.cs
  Complexity/Application/Repositories/Entities/UserProgressEntity.cs
  Complexity/Application/Repositories/ITaskRepository.cs
  Complexity/Application/Repositories/IUserRepository.cs
  Complexity/DataBase/DataBase.csproj
  Complexity/DataBase/MongoDatabaseInitializer.cs
  Complexity/DataBase/MongoTaskRepository.cs
  Complexity/DataBase/MongoUserRepository.cs
  Complexity/DataBase/Program.cs
  Complexity/Tests/ApplicationTests.cs
  Complexity/Tests/Mocks/TestTaskRepository.cs
  Complexity/Tests/Mocks/TestUserRepository.cs
Labels: backend, database

#65 Рандомизация и подстановка значений
  Complexity/Domain/Domain.csproj
  Complexity/Domain/Entities/TaskGenerators/TaskGenerator.cs
  Complexity/Domain/Entities/TaskGenerators/TemplateGenerator.cs
  Complexity/Tests/TemplateGenerator_Should.cs
  Complexity/Tests/Tests.csproj
Labels: backend

#67 Database Immutability;
  Complexity/Application/Application.cs
  Complexity/Application/DataBaseExtensions.cs
  Complexity/Application/DomainExtensions.cs
  Complexity/Application/Repositories/Entities/LevelProgressEntity.cs
  Complexity/Application/Repositories/Entities/TaskInfoEntity.cs
  Complexity/Application/Repositories/Entities/TopicProgressEntity.cs
  Complexity/Application/Repositories/Entities/UserEntity.cs
  Complexity/Application/Repositories/Entities/UserProgressEntity.cs
  Complexity/ComplexityWeb/Controllers/BotController.cs
  Complexity/ComplexityWeb/Controllers/UserDatabaseController.cs
  Complexity/ComplexityWeb/DTO/LevelInfoDTO.cs
  Complexity/ComplexityWeb/DTO/TaskInfoDTO.cs
  Complexity/ComplexityWeb/DTO/TopicInfoDTO.cs
  Complexity/ComplexityWeb/Program.cs
  Complexity/ComplexityWeb/Startup.cs
  Complexity/DataBase/DataBase.csproj
  Complexity/DataBase/MongoDatabaseInitializer.cs
  Complexity/DataBase/Program.cs
  Complexity/Domain/Domain.csproj
  Complexity/Domain/Entities/Level.cs
  Complexity/Domain/Entities/TaskGenerators/ExampleTaskGenerator.cs
  Complexity/Domain/Entities/TaskGenerators/TaskGenerator.cs
  Complexity/Domain/Entities/TaskGenerators/TemplateTaskGenerator.cs
  Complexity/Domain/Entities/Topic.cs
  Complexity/Infrastructure/DDD/Entity.cs
  Complexity/Infrastructure/DDD/EntityAttribute.cs
  Complexity/Infrastructure/DDD/Value.cs
  Complexity/Infrastructure/DDD/ValueAttribute.cs
  Complexity/Infrastructure/Result/Exceptions.cs
  Complexity/Infrastructure/Result/Result.cs
  Complexity/Infrastructure/Result/ResultCommonLogic.cs
  Complexity/Infrastructure/Result/ResultFailureException.cs
  Complexity/Infrastructure/Result/ResultMessages.cs
  Complexity/Infrastructure/Result/ResultSuccessException.cs
  Complexity/Tests/Domain_Should.cs
  Complexity/Tests/Tests.csproj
Labels: backend, enhancement

#68 MongoTaskRepository implementation;
  Complexity/Application/Repositories/ITaskRepository.cs
  Complexity/DataBase/DatabaseFiller.cs
  Complexity/DataBase/MongoDatabaseInitializer.cs
  Complexity/DataBase/MongoTaskRepository.cs
  Complexity/DataBase/MongoUserRepository.cs
  Complexity/DataBase/Program.cs
  Complexity/Domain/Domain.csproj
  Complexity/Domain/Entities/Level.cs
  Complexity/Domain/Entities/Topic.cs
  Complexity/Infrastructure/Infrastructure.csproj
  Complexity/Tests/Mocks/TestTaskRepository.cs
Labels: database

#70 Добавил селекторы генераторов
  Complexity/Application/Extensions/DataBaseExtensions.cs
  Complexity/Application/Extensions/DomainExtensions.cs
  Complexity/Application/Extensions/ObjectExtensions.cs
  Complexity/Application/IQuizService.cs
  Complexity/Application/ITaskGeneratorSelector.cs
  Complexity/Application/QuizService.cs
  Complexity/Application/Repositories/Entities/UserProgressEntity.cs
  Complexity/Application/Selectors/ITaskGeneratorSelector.cs
  Complexity/Application/Selectors/PrimitiveTaskGeneratorSelector.cs
  Complexity/Application/Selectors/ProgressTaskGeneratorSelector.cs
  Complexity/Application/Selectors/RandomTaskGeneratorSelector.cs
  Complexity/ComplexityWeb/Startup.cs
  Complexity/Tests/ApplicationTests.cs
  Complexity/Tests/Mocks/TestTaskGeneratorSelector.cs
Labels: backend, important

#80 Web api ffs
  Complexity/Application/QuizService.cs
  Complexity/ComplexityWeb/Controllers/QuizServiceController.cs
  Complexity/ComplexityWeb/Controllers/UserDatabaseController.cs
  Complexity/DataBase/DatabaseFiller.cs
  Complexity/Domain/Entities/TaskGenerators/TemplateTaskGenerator.cs
  Complexity/Infrastructure/Result/AsyncMaybeExtensions.cs
  Complexity/Infrastructure/Result/AsyncResultExtensionsBothOperands.cs
  Complexity/Infrastructure/Result/AsyncResultExtensionsLeftOperand.cs
  Complexity/Infrastructure/Result/AsyncResultExtensionsRightOperand.cs
  Complexity/Infrastructure/Result/MaybeExtensions.cs
  Complexity/Infrastructure/Result/Result.cs
  Complexity/Infrastructure/Result/ResultExtensions.cs
  Complexity/Tests/TemplateGenerator_Should.cs
Labels: backend
